sudo: required

dist: trusty

language: java

jdk:
  - oraclejdk8

addons:
    apt:
        packages:
        - oracle-java8-installer
        - git
        - cmake
        - libglpk-dev
        - libglpk-java

before_install:
  - echo glpkJava=$(dpkg -L libglpk-java | egrep 'libglpk_java.so$') > gradle.properties
  - echo glpk=$(dpkg -L libglpk-dev | egrep 'libglpk.so$') >> gradle.properties
  - wget https://github.com/libgit2/libgit2/archive/v0.26.0.tar.gz
  - tar -xaf v0.26.0.tar.gz
  - cd libgit2-0.26.0
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  - sudo cmake --build . --target install

notifications:
    irc:
        channels: "irc.freenode.org#jdime"
        skip_join: true
        use_notice: true
        on_success: change
        on_failure: always